### ISSUE TITLE
Test frameworks: 0 ran

### ISSUE THREAD

**Issue by rafaeltiveron** [brianjimenez/lightdock#13]
Probably test didn't work.

```
 ./run_tests.sh lib
******* Library tests *******

----------------------------------------------------------------------
Ran 0 tests in 0.002s

OK
```

**Comment by brianjimenez** [comment]
Please, in order to discard problems with nosetests, could you please:
`cd lightdock`
and then
`nosetests-2.7 --exe`

**Comment by rafaeltiveron** [comment]
Sure:

```
LightDock/lightdock $ nosetests-2.7 --exe
@> ProDy is configured: verbosity='info'
................................................................................             ...................F............................................................             ................................................................................             ...
======================================================================
FAIL: lightdock.test.mathutil.test_ellipsoid.TestEllipsoid.test_calculate_center
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/rafael/programas/LightDock/lightdock/test/mathutil/test_ellipsoid.             py", line 70, in test_calculate_center
    assert np.allclose(ellipsoid.center, [0.67988148, 0.50782009, 1.02831747], E             RROR_TOLERANCE)
AssertionError

----------------------------------------------------------------------
Ran 243 tests in 47.571s

FAILED (failures=1)
```

**Comment by brianjimenez** [comment]
Now it looks correct. Probably a _+x_ permission issue. There is one test which is not passing, but it's only a numerical instability issue, nothing to worry about. If you want to pass the rest of tests (regression), just remove execution permission to the .py files or just add in `run_tests.sh` the flag `--exe` after `nosetests-2.7`.

**Comment by rafaeltiveron** [comment]
Thank you. I ran the rest of tests and it is all ok.

**Comment by brianjimenez** [comment]
Thank you for your comment, I will also add `python-nose` to the list of dependencies.
